### ISSUE TITLE
App stay at "Please Wait..." 

### ISSUE THREAD

**Issue by djmMax** [cinder92/cordova-music-app#1]
![music-app](https://cloud.githubusercontent.com/assets/13382624/14587009/e02d6fc2-04a1-11e6-9bed-c8d8c102a931.png)

**Comment by cinder92** [comment]
did you check console? what error did you receive? if you are using android 6+ is not going to work, for now.

**Comment by djmMax** [comment]
Console : 
0     949056   error    No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.
1     949708   error    TypeError: Cannot read property 'coolMethod' of undefined
    at null.<anonymous> (http://192.168.138.1:8100/lib/music.app.min.js:1940:37)
    at Channel.subscribe (http://192.168.138.1:8100/cordova.js:760:11)
    at document.addEventListener (http://192.168.138.1:8100/cordova.js:133:34)
    at HTMLDocument.document.addEventListener (http://192.168.138.1:8100/cordova.js:1665:13)
    at searchFiles.vm.searchInDirectorys (http://192.168.138.1:8100/lib/music.app.min.js:1938:18)
    at getAllSongsfromDevice (http://192.168.138.1:8100/lib/music.app.min.js:1691:16)
    at http://192.168.138.1:8100/lib/music.app.min.js:1667:9
    at processQueue (http://192.168.138.1:8100/lib/ionic/js/ionic.bundle.js:27879:28)
    at http://192.168.138.1:8100/lib/ionic/js/ionic.bundle.js:27895:27
    at Scope.$eval (http://192.168.138.1:8100/lib/ionic/js/ionic.bundle.js:29158:28)
3     949741   log  
4     949744   error    TypeError: Cannot read property 'tintstatusbar' of undefined
    at http://192.168.138.1:8100/lib/music.app.min.js:46:25
    at processQueue (http://192.168.138.1:8100/lib/ionic/js/ionic.bundle.js:27879:28)
    at http://192.168.138.1:8100/lib/ionic/js/ionic.bundle.js:27895:27
    at Scope.$eval (http://192.168.138.1:8100/lib/ionic/js/ionic.bundle.js:29158:28)
    at Scope.$digest (http://192.168.138.1:8100/lib/ionic/js/ionic.bundle.js:28969:31)
    at http://192.168.138.1:8100/lib/ionic/js/ionic.bundle.js:29197:26
    at completeOutstandingRequest (http://192.168.138.1:8100/lib/ionic/js/ionic.bundle.js:18706:10)
    at http://192.168.138.1:8100/lib/ionic/js/ionic.bundle.js:18978:7
2     949719   error    Uncaught TypeError: Cannot read property 'tintstatusbar' of undefined, http://192.168.138.1:8100/lib/music.app.min.js, Line: 71
5     959135   warn     No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.

**Comment by cinder92** [comment]
hello again, you need to install all the plugins in README file 👍

**Comment by djmMax** [comment]
Please add all plugins in `package.json`

**Comment by cinder92** [comment]
check again 👍
